### ISSUE TITLE
User stays on homepage after Logging out  

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#12]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC
Short Description: User stays on homepage after Logging out  
Steps:  From home screen > select the sidebar> logging out> then select back key .
Observed: User stays on the homepage 
Expected: User should move to logging in page

**Comment by swiggins83** [comment]
Hitting back on login screen no longer returns the user to the home page. Fixed by a7918a49142aeab1a4a17738644c6bc7875adea2
