### ISSUE TITLE
Map Crash 

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#13]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC
Short Description: App crash when user delete one of the default markers 
Steps:  From home screen > select Maps> select one of the default markers> select delete  marker from the pop page> press  ok  
Observed: App crash and move to the home page 
Expected: Apps should not be crashed.

**Comment by dpkelly** [comment]
Issue Resolved. Removed the ability to delete markers when clicking on a marker that represents a stage.
