### ISSUE TITLE
 Back Softkey Issue

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#3]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC 

Short Description:  Back Softkey issue
Steps:  From the App Home page select back key 
Observed:  Back key takes the user to the logging page.
Expected: Back Keys should takes the user out of the App.

**Comment by swiggins83** [comment]
Back key now takes user out of app. Fixed dd008b55807703c116c348a25b5d1332a9af009a
