### ISSUE TITLE
Debug code should not shows under the color word

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#5]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC 

Short Description: Debug code should not shows under the color word.  
Steps:  From home page > selecting Map> press and hold on any area on the map to add location > add test and select ok  
Observed: after creating Marker On the top left corner and under the color test, the debug god is showing, 
Expected: The debug code should not show

**Comment by dpkelly** [comment]
Issue Resolved: Debug text box has been removed from the application.
