### ISSUE TITLE
App crash  

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#6]
Problem Type: SW
Priority: A
Occurrence: Always
Device used: HTC 

Short description: App crash  
Steps:  From the Home Page select Maps> then press on any Marker to Edit. > Select add  Geoefence or change Geofence. > select “ok”from the pop up message without adding or changing the radius. 
Observed:   App crash. 
Expected: App should not be crash.

**Comment by dpkelly** [comment]
Issue resolved. The app will now display an error message if the user attempts to create a geofence or change its size without entering in a number first.
