### ISSUE TITLE
Add and change Geoefence pop up does not have the distance unit showing to the user

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#7]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC 

Short Description:  Add and change Geoefence pop up does not have the distance unit showing to the user
Steps: From the Home Page select Maps> there press on any marker to Edit. > Select add Geoefence or change Geofence. > select ok from the pop up message without adding to changing the radius
Observed:  No distance unit showing to the user. 
Expected: The distance unit should show to the user.

**Comment by dpkelly** [comment]
Issue resolved. The input box now displays the units that the radius of the geofence will be to the user.
