### ISSUE TITLE
 user should not be able to Add Geofence when there is  Geofence added by the user

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#8]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC 

Short Description:  user should not be able to Add Geofence when there is  Geofence added by the user.
Steps: From the Home Page select Maps> then press on any Marker to Edit> (make sure that it has radius added in to it)> select Add Geofence > type number 
Observed:  user is able to add the radius. 
Expected: User should not be able to add the radius and, he should receive pop up indicate that the radius is exist.

**Comment by dpkelly** [comment]
Issue has been resolved. The user cannot select the add geofence option once they already have a geofence added. A message pops up in the application stating this to the user if attempted.
