### ISSUE TITLE
 user should not be able to change Geofence when there is no Geofence added by the user.

### ISSUE THREAD

**Issue by snissan** [swiggins83/cse-480#9]
Problem Type: SW
Priority: B
Occurrence: Always
Device used: HTC 

Short Description:  user should not be able to change Geofence when there is no Geofence added by the user.
Steps: From the Home Page select Maps> then press on any Marker to Edit> (make sure that it has radius added in to it)> select Add Geofence > type number 
Observed:  user is able to change the radius. 
Expected: User should not be able to change the radius and, the user should receive a pop up indicate that the radius is not exist

**Comment by dpkelly** [comment]
Issue has been resolved. The program now checks whether or not the user has added a geofence to a marker or not. If no marker is added, then the program will not allow the user to change the geofence, and displays a message stating that.
